name: Build JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['16', '18']
        include:
          - os: macos-latest
            node-version: 18
          - os: windows-latest
            node-version: 18
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Lint and test
      run: |
        npm run lint
        npm t
